# Generated by Django 4.1.5 on 2023-01-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curvi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='links',
            field=models.URLField(),
        ),
    ]
