# Generated by Django 4.1.5 on 2023-01-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curvi', '0002_alter_infos_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='list',
            new_name='skills',
        ),
    ]
