# Generated by Django 4.1.5 on 2023-01-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curvi', '0003_rename_list_skills_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
