# Generated by Django 4.1.5 on 2023-01-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curvi', '0004_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missions',
            name='title',
        ),
    ]
